/*
 * Automatically generated by ASN1 compiler.  Do not manually edit!
 *
 * ASN.1 parser for x509
 */

#include "asn1_ber_bytecode.h"
#include "x509.h"

enum x509_actions {
	ACT_do_algorithm = 0,
	ACT_do_attribute_type = 1,
	ACT_do_attribute_value = 2,
	ACT_do_extension_id = 3,
	ACT_do_extensions = 4,
	ACT_do_issuer = 5,
	ACT_do_serialnumber = 6,
	ACT_do_signature = 7,
	ACT_do_subject = 8,
	ACT_do_subject_public_key_info = 9,
	ACT_do_validity_not_after = 10,
	ACT_do_validity_not_before = 11,
	ACT_do_version = 12,
	NR__x509_actions = 13
};

static const asn1_action_t x509_action_table[NR__x509_actions] = {
	[   0] = do_algorithm,
	[   1] = do_attribute_type,
	[   2] = do_attribute_value,
	[   3] = do_extension_id,
	[   4] = do_extensions,
	[   5] = do_issuer,
	[   6] = do_serialnumber,
	[   7] = do_signature,
	[   8] = do_subject,
	[   9] = do_subject_public_key_info,
	[  10] = do_validity_not_after,
	[  11] = do_validity_not_before,
	[  12] = do_version,
};

static const unsigned char x509_machine[] = {
	// Certificate
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	// TBSCertificate
	[   2] =  ASN1_OP_MATCH,
	[   3] =  _tag(UNIV, CONS, SEQ),
	[   4] =   ASN1_OP_MATCH_JUMP_OR_SKIP,		// version
	[   5] =   _tagn(CONT, CONS,  0),
	[   6] =   _jump_target(67),
	// CertificateSerialNumber
	[   7] =   ASN1_OP_MATCH_ACT,
	[   8] =   _tag(UNIV, PRIM, INT),
	[   9] =   _action(ACT_do_serialnumber),
	// AlgorithmIdentifier
	[  10] =   ASN1_OP_MATCH_JUMP,
	[  11] =   _tag(UNIV, CONS, SEQ),
	[  12] =   _jump_target(72),		// --> AlgorithmIdentifier
	[  13] =   ASN1_OP_ACT,
	[  14] =   _action(ACT_do_signature),
	// Name
	[  15] =   ASN1_OP_MATCH_JUMP,
	[  16] =   _tag(UNIV, CONS, SEQ),
	[  17] =   _jump_target(78),		// --> Name
	[  18] =   ASN1_OP_ACT,
	[  19] =   _action(ACT_do_issuer),
	// Validity
	[  20] =   ASN1_OP_MATCH,
	[  21] =   _tag(UNIV, CONS, SEQ),
	// Time
	[  22] =    ASN1_OP_MATCH_OR_SKIP,		// utcTime
	[  23] =    _tag(UNIV, PRIM, UNITIM),
	[  24] =    ASN1_OP_COND_MATCH_OR_SKIP,		// generalTime
	[  25] =    _tag(UNIV, PRIM, GENTIM),
	[  26] =    ASN1_OP_COND_FAIL,
	[  27] =    ASN1_OP_ACT,
	[  28] =    _action(ACT_do_validity_not_before),
	// Time
	[  29] =    ASN1_OP_MATCH_OR_SKIP,		// utcTime
	[  30] =    _tag(UNIV, PRIM, UNITIM),
	[  31] =    ASN1_OP_COND_MATCH_OR_SKIP,		// generalTime
	[  32] =    _tag(UNIV, PRIM, GENTIM),
	[  33] =    ASN1_OP_COND_FAIL,
	[  34] =    ASN1_OP_ACT,
	[  35] =    _action(ACT_do_validity_not_after),
	[  36] =   ASN1_OP_END_SEQ,
	// Name
	[  37] =   ASN1_OP_MATCH_JUMP,
	[  38] =   _tag(UNIV, CONS, SEQ),
	[  39] =   _jump_target(78),		// --> Name
	[  40] =   ASN1_OP_ACT,
	[  41] =   _action(ACT_do_subject),
	// SubjectPublicKeyInfo
	[  42] =   ASN1_OP_MATCH,
	[  43] =   _tag(UNIV, CONS, SEQ),
	// AlgorithmIdentifier
	[  44] =    ASN1_OP_MATCH_JUMP,
	[  45] =    _tag(UNIV, CONS, SEQ),
	[  46] =    _jump_target(72),		// --> AlgorithmIdentifier
	[  47] =    ASN1_OP_MATCH,		// subjectPublicKey
	[  48] =    _tag(UNIV, PRIM, BTS),
	[  49] =   ASN1_OP_END_SEQ,
	[  50] =   ASN1_OP_ACT,
	[  51] =   _action(ACT_do_subject_public_key_info),
	// UniqueIdentifier
	[  52] =   ASN1_OP_MATCH_OR_SKIP,
	[  53] =   _tagn(CONT, PRIM,  1),
	// UniqueIdentifier
	[  54] =   ASN1_OP_MATCH_OR_SKIP,
	[  55] =   _tagn(CONT, PRIM,  2),
	[  56] =   ASN1_OP_MATCH_JUMP_OR_SKIP,		// extensions
	[  57] =   _tagn(CONT, CONS,  3),
	[  58] =   _jump_target(93),
	[  59] =  ASN1_OP_END_SEQ,
	// AlgorithmIdentifier
	[  60] =  ASN1_OP_MATCH_JUMP,
	[  61] =  _tag(UNIV, CONS, SEQ),
	[  62] =  _jump_target(72),		// --> AlgorithmIdentifier
	[  63] =  ASN1_OP_MATCH,		// signature
	[  64] =  _tag(UNIV, PRIM, BTS),
	[  65] = ASN1_OP_END_SEQ,
	[  66] = ASN1_OP_COMPLETE,

	// Version
	[  67] =  ASN1_OP_MATCH_ACT,
	[  68] =  _tag(UNIV, PRIM, INT),
	[  69] =  _action(ACT_do_version),
	[  70] = ASN1_OP_END_SEQ,
	[  71] = ASN1_OP_RETURN,

	[  72] =  ASN1_OP_MATCH_ACT,		// algorithm
	[  73] =  _tag(UNIV, PRIM, OID),
	[  74] =  _action(ACT_do_algorithm),
	[  75] =  ASN1_OP_MATCH_ANY,		// parameters
	[  76] = ASN1_OP_END_SEQ,
	[  77] = ASN1_OP_RETURN,

	// RelativeDistinguishedName
	[  78] =  ASN1_OP_MATCH,
	[  79] =  _tag(UNIV, CONS, SET),
	// AttributeValueAssertion
	[  80] =   ASN1_OP_MATCH,
	[  81] =   _tag(UNIV, CONS, SEQ),
	[  82] =    ASN1_OP_MATCH_ACT,		// attributeType
	[  83] =    _tag(UNIV, PRIM, OID),
	[  84] =    _action(ACT_do_attribute_type),
	[  85] =    ASN1_OP_MATCH_ANY_ACT,		// attributeValue
	[  86] =    _action(ACT_do_attribute_value),
	[  87] =   ASN1_OP_END_SEQ,
	[  88] =  ASN1_OP_END_SET_OF,
	[  89] =  _jump_target(80),
	[  90] = ASN1_OP_END_SEQ_OF,
	[  91] = _jump_target(78),
	[  92] = ASN1_OP_RETURN,

	// Extensions
	[  93] =  ASN1_OP_MATCH,
	[  94] =  _tag(UNIV, CONS, SEQ),
	// Extension
	[  95] =   ASN1_OP_MATCH,
	[  96] =   _tag(UNIV, CONS, SEQ),
	[  97] =    ASN1_OP_MATCH_ACT,		// extId
	[  98] =    _tag(UNIV, PRIM, OID),
	[  99] =    _action(ACT_do_extension_id),
	[ 100] =    ASN1_OP_MATCH_OR_SKIP,		// critical
	[ 101] =    _tag(UNIV, PRIM, BOOL),
	[ 102] =    ASN1_OP_MATCH,		// extValue
	[ 103] =    _tag(UNIV, PRIM, OTS),
	[ 104] =   ASN1_OP_END_SEQ,
	[ 105] =  ASN1_OP_END_SEQ_OF,
	[ 106] =  _jump_target(95),
	[ 107] =  ASN1_OP_ACT,
	[ 108] =  _action(ACT_do_extensions),
	[ 109] = ASN1_OP_END_SEQ,
	[ 110] = ASN1_OP_RETURN,
};

const struct asn1_decoder x509_decoder = {
	.machine = x509_machine,
	.machlen = sizeof(x509_machine),
	.actions = x509_action_table,
};
